kind: wasmer.io/App.v0
owner: aliyazbk
name: darin-store-backend
package: .

annotations:
  anybuild.run/config:
    commands:
      start: php -S 0.0.0.0:8080 -t public
    composer_build_script: post-update-cmd
    composer_enable: true
    name: out
    node_build_command: npm run build
    node_install_inputs:
      - package.json
    node_package_manager: npm
    npm_version: '11'
    php_framework: laravel
    php_public_dir: public
    phpix: true